name = "openai-proxy"
type = "javascript"

account_id = "your-cloudflare-account-id"
workers_dev = true

compatibility_date = "2022-03-22"

[vars]
OPENAI_API_KEY = "sk-..."  # your actual OpenAI key here
